### ISSUE TITLE
Typo in checking jquery emitter instance

### ISSUE THREAD

**Issue by apiep** [devanshj/rxjs-from-emitter#1]
Hi there, I wonder if there is a typo on `isJqueryEmitter` function which are checking for `addListener` and `removeListener` while in the implementation it uses `on` and `off` instead.

**Comment by devanshj** [comment]
@apiep Ah yes that's a typo, thanks for reporting! I'll fix it. Also just curious from where did you come know to about this package?

**Comment by apiep** [comment]
Oh I know about this package from your PR and issue on xstream and rxjs discussion about `fromEvent`

**Comment by devanshj** [comment]
@apiep Oh Okay!
